// Country names
window.uiTexts = window.uiTexts || {};
window.uiTexts.countries = {
    en: {
        countries: {
            'Afghanistan': 'Afghanistan',
            'Albania': 'Albania',
            'Algeria': 'Algeria',
            'Argentina': 'Argentina',
            'Australia': 'Australia',
            'Austria': 'Austria',
            'Bangladesh': 'Bangladesh',
            'Belgium': 'Belgium',
            'Brazil': 'Brazil',
            'Bulgaria': 'Bulgaria',
            'Canada': 'Canada',
            'Chile': 'Chile',
            'China': 'China',
            'Colombia': 'Colombia',
            'Croatia': 'Croatia',
            'Czech Republic': 'Czech Republic',
            'Denmark': 'Denmark',
            'Egypt': 'Egypt',
            'Finland': 'Finland',
            'France': 'France',
            'Germany': 'Germany',
            'Greece': 'Greece',
            'Hungary': 'Hungary',
            'India': 'India',
            'Indonesia': 'Indonesia',
            'Iran': 'Iran',
            'Iraq': 'Iraq',
            'Ireland': 'Ireland',
            'Italy': 'Italy',
            'Japan': 'Japan',
            'Jordan': 'Jordan',
            'Kenya': 'Kenya',
            'Kuwait': 'Kuwait',
            'Lebanon': 'Lebanon',
            'Malaysia': 'Malaysia',
            'Mexico': 'Mexico',
            'Morocco': 'Morocco',
            'Netherlands': 'Netherlands',
            'New Zealand': 'New Zealand',
            'Nigeria': 'Nigeria',
            'Norway': 'Norway',
            'Pakistan': 'Pakistan',
            'Peru': 'Peru',
            'Philippines': 'Philippines',
            'Poland': 'Poland',
            'Portugal': 'Portugal',
            'Qatar': 'Qatar',
            'Romania': 'Romania',
            'Russia': 'Russia',
            'Saudi Arabia': 'Saudi Arabia',
            'Singapore': 'Singapore',
            'South Africa': 'South Africa',
            'South Korea': 'South Korea',
            'Spain': 'Spain',
            'Sweden': 'Sweden',
            'Switzerland': 'Switzerland',
            'Syria': 'Syria',
            'Thailand': 'Thailand',
            'Turkey': 'Turkey',
            'Ukraine': 'Ukraine',
            'United Arab Emirates': 'United Arab Emirates',
            'United Kingdom': 'United Kingdom',
            'United States': 'United States',
            'Venezuela': 'Venezuela',
            'Vietnam': 'Vietnam',
            'Yemen': 'Yemen'
        }
    },
    fa: {
        countries: {
            'Afghanistan': 'افغانستان',
            'Albania': 'آلبانی',
            'Algeria': 'الجزایر',
            'Argentina': 'آرژانتین',
            'Australia': 'استرالیا',
            'Austria': 'اتریش',
            'Bangladesh': 'بنگلادش',
            'Belgium': 'بلژیک',
            'Brazil': 'برزیل',
            'Bulgaria': 'بلغارستان',
            'Canada': 'کانادا',
            'Chile': 'شیلی',
            'China': 'چین',
            'Colombia': 'کلمبیا',
            'Croatia': 'کرواسی',
            'Czech Republic': 'جمهوری چک',
            'Denmark': 'دانمارک',
            'Egypt': 'مصر',
            'Finland': 'فنلاند',
            'France': 'فرانسه',
            'Germany': 'آلمان',
            'Greece': 'یونان',
            'Hungary': 'مجارستان',
            'India': 'هند',
            'Indonesia': 'اندونزی',
            'Iran': 'ایران',
            'Iraq': 'عراق',
            'Ireland': 'ایرلند',
            'Italy': 'ایتالیا',
            'Japan': 'ژاپن',
            'Jordan': 'اردن',
            'Kenya': 'کنیا',
            'Kuwait': 'کویت',
            'Lebanon': 'لبنان',
            'Malaysia': 'مالزی',
            'Mexico': 'مکزیک',
            'Morocco': 'مراکش',
            'Netherlands': 'هلند',
            'New Zealand': 'نیوزیلند',
            'Nigeria': 'نیجریه',
            'Norway': 'نروژ',
            'Pakistan': 'پاکستان',
            'Peru': 'پرو',
            'Philippines': 'فیلیپین',
            'Poland': 'لهستان',
            'Portugal': 'پرتغال',
            'Qatar': 'قطر',
            'Romania': 'رومانی',
            'Russia': 'روسیه',
            'Saudi Arabia': 'عربستان سعودی',
            'Singapore': 'سنگاپور',
            'South Africa': 'آفریقای جنوبی',
            'South Korea': 'کره جنوبی',
            'Spain': 'اسپانیا',
            'Sweden': 'سوئد',
            'Switzerland': 'سوئیس',
            'Syria': 'سوریه',
            'Thailand': 'تایلند',
            'Turkey': 'ترکیه',
            'Ukraine': 'اوکراین',
            'United Arab Emirates': 'امارات متحده عربی',
            'United Kingdom': 'بریتانیا',
            'United States': 'ایالات متحده آمریکا',
            'Venezuela': 'ونزوئلا',
            'Vietnam': 'ویتنام',
            'Yemen': 'یمن'
        }
    }
};
