// UI interface texts
window.uiTexts = window.uiTexts || {};
window.uiTexts.interface = {
    en: {
        title: '🌅 Sunset Clock',
        clockLabel: 'Time since sunset',
        countryLabel: 'Country:',
        cityLabel: 'City:',
        saveBtn: 'Save Location',
        locationText: 'Loading location...',
        pleaseEnterLocation: 'Please enter your location',
        searchCountry: 'Search country...',
        selectCountryFirst: 'Select country first...',
        searchCity: 'Search city...',
        loadingCities: 'Loading cities...',
        noCountriesFound: 'No countries found',
        noCitiesFound: 'No cities found',
        pleaseSelectBoth: 'Please select both country and city',
        pleaseSelectValidCountry: 'Please select a valid country from the list',
        locationNotSet: 'Location not set',
        fetchingSunset: 'Fetching sunset time...',
        usingCached: 'Using cached sunset time',
        sunsetUpdated: 'Sunset time updated',
        errorFetching: 'Error fetching sunset time. Using cached data if available.',
        usingCachedOutdated: 'Using cached sunset time (may be outdated)',
        unableToLoad: 'Unable to load sunset time',
        offline: 'Offline - using cached sunset time',
        estimatedOffline: 'Estimated sunset time (offline)',
        settings: '⚙️',
        aboutTitle: 'About Sunset Clock',
        developerContactTitle: 'Developer Contact',
        contactWebsiteText: 'Website',
        contactLinkText: 'Contact'
    },
    fa: {
        title: '🌅 ساعت غروب‌کوک',
        clockLabel: 'زمان از غروب',
        countryLabel: 'کشور:',
        cityLabel: 'شهر:',
        saveBtn: 'ذخیره موقعیت',
        locationText: 'در حال بارگذاری موقعیت...',
        pleaseEnterLocation: 'لطفاً موقعیت خود را وارد کنید',
        searchCountry: 'جستجوی کشور...',
        selectCountryFirst: 'ابتدا کشور را انتخاب کنید...',
        searchCity: 'جستجوی شهر...',
        loadingCities: 'در حال بارگذاری شهرها...',
        noCountriesFound: 'کشوری یافت نشد',
        noCitiesFound: 'شهری یافت نشد',
        pleaseSelectBoth: 'لطفاً کشور و شهر را انتخاب کنید',
        pleaseSelectValidCountry: 'لطفاً یک کشور معتبر از لیست انتخاب کنید',
        locationNotSet: 'موقعیت تنظیم نشده',
        fetchingSunset: 'در حال دریافت زمان غروب...',
        usingCached: 'استفاده از زمان غروب ذخیره شده',
        sunsetUpdated: 'زمان غروب به‌روزرسانی شد',
        errorFetching: 'خطا در دریافت زمان غروب. در صورت وجود، از داده‌های ذخیره شده استفاده می‌شود.',
        usingCachedOutdated: 'استفاده از زمان غروب ذخیره شده (ممکن است قدیمی باشد)',
        unableToLoad: 'امکان بارگذاری زمان غروب وجود ندارد',
        offline: 'آفلاین - استفاده از زمان غروب ذخیره شده',
        estimatedOffline: 'زمان غروب تخمینی (آفلاین)',
        settings: '⚙️',
        aboutTitle: 'درباره ساعت غروب',
        developerContactTitle: 'تماس با توسعه‌دهنده',
        contactWebsiteText: 'وب‌سایت',
        contactLinkText: 'تماس'
    }
};
